# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemachine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tm1617Skater',
            fields=[
                ('playerid', models.IntegerField(primary_key=True, serialize=False)),
                ('playername', models.CharField(max_length=255)),
                ('gp', models.IntegerField()),
                ('g', models.IntegerField()),
                ('a', models.IntegerField()),
                ('p', models.IntegerField()),
                ('pm', models.IntegerField()),
                ('pim', models.IntegerField()),
                ('s', models.IntegerField()),
                ('ppg', models.IntegerField()),
                ('ppa', models.IntegerField()),
                ('ppp', models.IntegerField()),
                ('shg', models.IntegerField()),
                ('sha', models.IntegerField()),
                ('shp', models.IntegerField()),
            ],
            options={
                'db_table': 'tm1617skater',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='season',
            table='season',
        ),
    ]
