# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemachine', '0003_skater1987_skater1988_skater1989_skater1990_skater1991_skater1992_skater1993_skater1994_skater1995_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalieSeasons',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('playername', models.CharField(blank=True, max_length=255, null=True)),
                ('toi', models.FloatField(blank=True, null=True)),
                ('sa', models.IntegerField(blank=True, null=True)),
                ('sv', models.IntegerField(blank=True, null=True)),
                ('w', models.IntegerField(blank=True, null=True)),
                ('l', models.IntegerField(blank=True, null=True)),
                ('sow', models.IntegerField(blank=True, null=True)),
                ('sol', models.IntegerField(blank=True, null=True)),
                ('otw', models.IntegerField(blank=True, null=True)),
                ('otl', models.IntegerField(blank=True, null=True)),
                ('t', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goalieseasons',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='skater1988',
            table='skater1988',
        ),
        migrations.AlterModelTable(
            name='skater1989',
            table='skater1989',
        ),
        migrations.AlterModelTable(
            name='skater1990',
            table='skater1990',
        ),
        migrations.AlterModelTable(
            name='skater1991',
            table='skater1991',
        ),
        migrations.AlterModelTable(
            name='skater1992',
            table='skater1992',
        ),
        migrations.AlterModelTable(
            name='skater1993',
            table='skater1993',
        ),
        migrations.AlterModelTable(
            name='skater1994',
            table='skater1994',
        ),
        migrations.AlterModelTable(
            name='skater1995',
            table='skater1995',
        ),
        migrations.AlterModelTable(
            name='skater1996',
            table='skater1996',
        ),
        migrations.AlterModelTable(
            name='skater1997',
            table='skater1997',
        ),
        migrations.AlterModelTable(
            name='skater1998',
            table='skater1998',
        ),
        migrations.AlterModelTable(
            name='skater1999',
            table='skater1999',
        ),
        migrations.AlterModelTable(
            name='skater2000',
            table='skater2000',
        ),
        migrations.AlterModelTable(
            name='skater2001',
            table='skater2001',
        ),
        migrations.AlterModelTable(
            name='skater2002',
            table='skater2002',
        ),
        migrations.AlterModelTable(
            name='skater2003',
            table='skater2003',
        ),
        migrations.AlterModelTable(
            name='skater2004',
            table='skater2004',
        ),
        migrations.AlterModelTable(
            name='skater2005',
            table='skater2005',
        ),
        migrations.AlterModelTable(
            name='skater2006',
            table='skater2006',
        ),
        migrations.AlterModelTable(
            name='skater2007',
            table='skater2007',
        ),
        migrations.AlterModelTable(
            name='skater2008',
            table='skater2008',
        ),
        migrations.AlterModelTable(
            name='skater2009',
            table='skater2009',
        ),
        migrations.AlterModelTable(
            name='skater2010',
            table='skater2010',
        ),
        migrations.AlterModelTable(
            name='skater2011',
            table='skater2011',
        ),
        migrations.AlterModelTable(
            name='skater2012',
            table='skater2012',
        ),
        migrations.AlterModelTable(
            name='skater2013',
            table='skater2013',
        ),
        migrations.AlterModelTable(
            name='skater2014',
            table='skater2014',
        ),
        migrations.AlterModelTable(
            name='skater2015',
            table='skater2015',
        ),
    ]
