# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemachine', '0004_auto_20170721_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skaterseasons',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('playername', models.CharField(blank=True, max_length=255, null=True)),
                ('gp', models.IntegerField(blank=True, null=True)),
                ('goals', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('plusminus', models.IntegerField(blank=True, null=True)),
                ('pim', models.IntegerField(blank=True, null=True)),
                ('shots', models.IntegerField(blank=True, null=True)),
                ('ppg', models.IntegerField(blank=True, null=True)),
                ('ppa', models.IntegerField(blank=True, null=True)),
                ('shg', models.IntegerField(blank=True, null=True)),
                ('sha', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'skaterseasons',
                'managed': False,
            },
        ),
    ]
