# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemachine', '0005_skaterseasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedSSeasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.IntegerField(blank=True, null=True)),
                ('gp', models.IntegerField(blank=True, null=True)),
                ('g', models.IntegerField(blank=True, null=True)),
                ('a', models.IntegerField(blank=True, null=True)),
                ('p', models.IntegerField(blank=True, null=True)),
                ('pim', models.IntegerField(blank=True, null=True)),
                ('s', models.IntegerField(blank=True, null=True)),
                ('evg', models.IntegerField(blank=True, null=True)),
                ('eva', models.IntegerField(blank=True, null=True)),
                ('evp', models.IntegerField(blank=True, null=True)),
                ('ppg', models.IntegerField(blank=True, null=True)),
                ('ppa', models.IntegerField(blank=True, null=True)),
                ('ppp', models.IntegerField(blank=True, null=True)),
                ('shg', models.IntegerField(blank=True, null=True)),
                ('sha', models.IntegerField(blank=True, null=True)),
                ('shp', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'skaterseasons',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='skaterseasons',
            options={},
        ),
    ]
