# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timemachine', '0006_auto_20170721_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skaterseasons',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='convertedsseasons',
            table='convertedsseasons',
        ),
    ]
