# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timemachine', '0007_auto_20170721_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convertedsseasons',
            options={'managed': True},
        ),
    ]
