# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemachine', '0008_auto_20170722_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convertedsseasons',
            old_name='player',
            new_name='playerid',
        ),
        migrations.AddField(
            model_name='convertedsseasons',
            name='playername',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='convertedsseasons',
            name='seasonid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='convertedsseasons',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
